name: ioBroker
version: "1.0"
slug: iobroker
description: "ioBroker Docker Container als Home Assistant Add-on"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
startup: application
boot: auto
host_docker: true
privileged: true
host_network: false
options: {}
schema: {}
ports:
  "8081/tcp": 8081
