name: ioBroker
version: v10.0.0
slug: iobroker
description: ioBroker als Home Assistant Add-on
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
startup: application
boot: auto
ingress: true
ingress_port: 8081
panel_icon: mdi:home-automation
panel_title: ioBroker
panel_admin: true
image: buanet/iobroker:v10.0.0
map:
  - addon_config:rw
ports:
  "8081/tcp": 8081
  "1883/tcp": 18883
ports_description:
  "8081/tcp": "ioBroker Admin UI"
  "18883/tcp": "MQTT Broker Port (optional)"
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
