name: "ioBroker"
version: "1.0"
slug: "iobroker"
description: "ioBroker als Home Assistant Add-on"
url: "https://github.com/alientim/HA-ioBroker"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
startup: "system"
boot: "auto"
host_docker: true
init: false
ports:
  8081/tcp: 8081
options: {}
schema: {}
